# Site settings
title: Nick Clarkson
email: nick@clarkson.io
description: Technical Director and Creative Technologist based in Bristol and Bath
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://clar.ky" # the base hostname & protocol for your site
twitter_username: t_pk
github_username:  netotaku

# Build settings
markdown: kramdown
